export const SITE_META = {
  NAME: `PlayGames.mobi`,
  URL: `https://playgames.mobi`,
  DOMAIN: `playgames.mobi`,
};

export const MODE = `dev`;

export const ADS_ID = `ca-pub-9062459637265650`;

export const IMAGE_FORMAT = `webp`;

export const IMAGE_PATH = `https://cdn.iwantalipstick.com/gameicon2/`;

export const CHANNEL = `tpal`;

export const GAME_PATH = `https://cdn.${SITE_META.DOMAIN}/newgames/minigame.html?platform=${CHANNEL}&appid=`;

export const ADS_SLOT_ID = {
  home: `4970224950`,
  category: `3151491220`,
  detail: `7264381652`,
};

export const SELECTED_GAMES = [
  "Knife",
  "JumpSmash",
  "CrazyMoto",
  "CrazyKart3D",
  "FireTheGun",
  "FeverRacing",
  "ColorBall3D",
  "CrazyKnife",
  "BoardTheTrain",
  "MrRacer",
  "BigSword",
  "HiTaxi",
  "TrafficRun",
  "MrBullet",
  "LetMeIn",
  "SnakeGo",
  "DessertConnect",
  "SwiftRider",
  "CrackShot",
  "CrazyGunfight",
  "GoldenGlove",
  "ColorRing",
  "PianoKeys",
  "ArchersKing",
  "MyBabyCare",
  "DartsKing3D",
  "CrazyRace",
  "BallIsComing",
  "HungyBunny",
  "TheSameWorld",
  "SuperMiner",
  "BounceShooter",
  "HillRacing",
  "BatterKing",
  "BlockGun3D",
  "ZombieSurvival",
  "FruitMonster",
  "FierceCity",
  "IronAttack",
  "AceMan",
  "AirBrawl",
  "BumbleShooter",
  "AmazingRoad",
  "RainbowSplash",
  "MagicParkour",
  "CrazyDrift",
  "FisherMan",
  "FruitsFall",
  "RocketJump",
  "MagicPaint",
  "GlidingCharger",
  "RoadCharger",
  "ArcheryMaster",
  "UltraDrift",
  "SharkisComing",
  "PuppyRun",
  "PenguinDash",
  "MonsterCrash",
  "DeathJump",
  "HungryMonster",
  "HungryAnimals",
  "JumpingMonkey",
  "MergeKill",
  "CrazyTrain3D",
  "CrazyHammer",
  "VirusWar",
  "TrappedPirate",
  "StickmanVsZombies",
  "FingerCannon",
  "BulletMan",
  "KnockBalls",
  "GunShooter",
  "MergeGuns3D",
  "BulletMaster3D",
  "CrashTower3D",
  "TowerBlast3D",
  "ShootSmash",
  "ShootingCubes",
  "BubbleBlast",
  "FlyPass",
  "KillAllZombies",
  "CollectColorfulBalls",
  "KimbapRun",
  "AnipopLink",
  "PetsMatch",
  "HappyBilliards",
  "SuperThrow",
  "CrazyBomb",
  "HelpTheZombie",
  "SaveThePets",
  "SoccerHero",
  "TableTennisChampionship",
  "4096",
  "MagicDonuts",
  "SolitaireClassic",
  "DeathRun",
  "IdleRestaurantTycoon",
  "ImEmpire",
  "MahjongConnect",
  "Mining",
  "MiningMaster",
  "Transform",
  "DefenseTower",
  "DragonCrush",
  "TwistyRoad",
  "ZooBlast",
  "ZumaMarbles",
  "BlockPuzzle",
  "CrazyPortal",
  "DressQueen",
  "MahjongLink3D",
  "MergeAndDefense",
  "MergeMagicJewellery",
  "PetRun",
  "SkyRunning3D",
  "SuperGolf",
  "TowerDefenseX",
  "PandaRescue",
  "FillTheGlass",
  "MagicNumber",
  "PlantBeatZombies",
  "AirHockey3D",
  "MyBowling3D",
  "Chess3D",
  "8BallKing",
  "MyUnicorn",
  "MagicJigsaw",
  "FairyTalesPuzzle",
  "PipePuzzle",
  "TrafficPassing",
  "SplittingCells",
  "FeedMaster",
  "FinalBattle",
  "FrozenMagic",
  "SuperDefense",
  "Super2048",
  "BubblePop",
  "RelivedLife",
  "CandyHit",
  "MergeCat",
  "MelodyLink",
  "PuzzleVenture",
  "BrainMaster",
  "AntRun",
  "BombingTime",
  "BlockMaze",
  "HappyTetris",
  "MagicPainter",
  "MatchingCook",
  "ColorBead",
  "ColorSplash",
  "RollingAgent",
  "RushingRover",
  "SkatingMaster",
  "LittleFarm",
  "Hurricane",
  "WoodIsland",
  "InfiDefense",
  "BoomingPlant",
  "PowerShooter",
  "GoldenBoot",
  "RushAndFire",
  "BestSniper",
  "SnakeHit",
  "BraveArcher",
  "TinyWar",
  "ShootingStar",
  "ColorHammer",
  "BilliardKing",
  "FuryEdge",
  "CutMaster",
  "CountingMaster",
  "CleverRescue",
  "BigEater",
  "CrayonPop",
  "ColorCrash",
  "BuilderRun",
  "WildRoll",
  "RoofRunner",
  "MadEraser",
  "HarvestStory",
  "CityExpress",
  "FreeFall",
];

export const EXCLUDED_GAMES = [];

export const FEATURED_GAMES = [``];
